etherfi-protocol/smart-contracts

- release/abis/BNFT.json
- release/abis/EtherFiNodesManager.json
- release/abis/LiquidityPool.json
- release/abis/TNFT.json
- script/deploys/DeployImplementationContracts.s.sol
- script/deploys/DeployPhaseTwo.s.sol
- src/EtherFiNodesManager.sol
For Work In Progress Pull Requests, please use the Draft PR feature,
see https://github.blog/2019-02-14-introducing-draft-pull-requests/ for further details.
For a timely review/response, please avoid force-pushing additional
commits if your PR already received reviews or comments.
Before submitting a Pull Request, please ensure you've done the following:
- 👷‍♀️ Create small PRs. In most cases this will be possible.
- ✅ Provide tests for your changes.
- 📝 Use descriptive commit messages.
- 📗 Update any related documentation and include any relevant screenshots.
For pull requests that relate or close an issue, please include them
below.  We like to follow [Github's guidance on linking issues to pull requests](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-re …
> fixed merge conflicts on cherry pick of hash commit from dappContracts

- test/EtherFiOracle.t.sol
Added a unit test scenario with multiple commitee members
> [Unit Test] Add a consensus scenario unit test

- .gitmodules
- lib/BucketLimiter.sol
- script/deploys/BucketRateLimiter.s.sol
- script/deploys/DeployBucketLimiter.s.sol
- script/upgrades/BucketRateLimiter.s.sol
- script/upgrades/Liquifier.s.sol
- src/BucketRateLimiter.sol
- src/interfaces/IRateLimiter.sol
- test/BucketRaterLimiter.t.sol
- test/EigenLayerIntegration.t.sol
- Used a library by Paladin. Thanks! https://gist.github.com/JorgeAtPaladin/9f173900423c107930f27195dd2c78e4
- To be used for SyncPool contracts
> add bucket rate limiter

- src/WeETH.sol
Fixes the `getRate` description.
> Fix getRate description

- .gitignore
- README.md
- certora/config/EtherFiOracle.conf
- certora/specs/EtherFiOracle.spec
-formally verify tracking active members
-check only valid members can submit report
-Check state correctly updated when report submitted
https://prover.certora.com/output/761563/2dc1c8a2d5214ced8e83a82364b8b8f5?anonymousKey=882c889dff8cf829a71352f2771c2703bb9d15e3
> Certora Testing Oracle

- script/deploys/DeployLiquifier.s.sol
- src/Liquifier.sol
- test/Liquifier.t.sol
- test/TestSetup.sol
- test/a.sol
They need to go thorugh the EFIP and get approved again. fixing the tests accordingly
This PR will match the code in the `master` repo with the current deployed https://etherscan.io/address/0x9FFDF407cDe9a93c47611799DA23924Af3EF764F
> Revert the updates on Liquiifier

- src/EETH.sol
- src/WeETH.sol
- test/EETH.t.sol
- test/TestSetup.sol
- test/WeETH.t.sol
- Implements [EFIP-5](https://github.com/etherfi-protocol/smart-contracts/blob/master/proposals/EFIP-5.md) functionality and tests
- Makes comment style consistent between `eETH` and `weETH`
> [EFIP-5] {Permit Whitelist, Transfer Blacklist}

- proposals/EFIP-8.md
the proper oracle implementation must follow :) @vvalecha519
> [EFIP-8] Async Admin Task Execution for Validator Management

- proposals/EFIP-11.md
- proposals/EFIP-7.md
- proposals/EFIP-8.md
- src/EETH.sol
- src/EtherFiNode.sol
- src/WeETH.sol
- src/interfaces/IEtherFiNodesManager.sol
- test/EETH.t.sol
- test/EtherFiNodesManager.t.sol
- test/TestSetup.sol
- test/WeETH.t.sol
- extend `isValidSignature` to use the role registry
- move efip-8 to efip-11 due to conflict
- handle merge conflicts
> merge master

- proposals/EFIP-7.md
- proposals/references/NM-0217-efip1271-for-etherfinode-contract.md
The reported [Best Practice] will be handled during the Certora audit
> Add audit review for efip-7 implementation

- src/EETH.sol
- src/WeETH.sol
- Cache array length outside of loop 
- Add whitelist events
- Removing redundant console import
> [Chore] [EFIP-5] - acknowledge findings from harborn audit 

- proposals/EFIP-14.md
This PR introduces an EFIP for improving our permissions and security across the protocol by using a central Role Registry contract
> [EFIP-14] Role Registry proposal

- proposals/EFIP-10.md
- proposals/references/NM-0217-whitelisted-delegate-calls-for-efip-10.md
- src/EtherFiNodesManager.sol
- test/EigenLayerIntegration.t.sol
- test/EtherFiNode.t.sol
- test/EtherFiNodesManager.t.sol
- merging the implementation
- uploaded the audit review
> [EFIP-10] Whitelisted Delegate calls for EtherFiNode/EigenPod

- src/WithdrawRequestNFT.sol
- test/MembershipManager.t.sol
- test/WithdrawRequestNFT.t.sol
Handle https://github.com/etherfi-protocol/smart-contracts/issues/24
> fix the accounting error in dust share for withdrawal requests

- src/helpers/EtherFiViewer.sol
- src/interfaces/IEtherFiNodesManager.sol
a helper function to count the balance of safes/eigenpods being unused
> add EtherFiViewer.aggregatedBalanceOfUnusedSafes

- src/DepositAdapter.sol
- test/DepositAdapter.t.sol
- Fixes permit expire issue
- omitted the recommended check for allowance as the `transferFrom` in the next line will check and revert
> Deposit Adapter Audit Info 2 Fix

- src/EETH.sol
- test/EETH.t.sol
> [Certora][M-12] burn shares fix

- src/EtherFiNodesManager.sol
remove onlyOwner modifier since it is already scoped to a particular role
> [Certora][I-03] fix double role check

- src/RoleRegistry.sol
- The role registry has already be deployed to mainnet
- Importing here from staging so we can develop against it on master branch
> [Chore] Import role registry

- src/eigenlayer-interfaces/IEigenPod.sol
- test/eigenlayer-mocks/EigenPodManagerMock.sol
- test/eigenlayer-mocks/EigenPodMock.sol
Minimal eigenpod mock contract  with setters for the return values of all the functions are protocol uses
> eigenpod mock with setters for required storage vars

- test/eigenlayer-mocks/EigenPodManagerMock.sol
- test/eigenlayer-mocks/EigenPodMock.sol
Update mocks for slashing release
> update mocks for slashing release

- script/README_V3_VERIFICATION.md
- script/VerifyV3Upgrade.s.sol
Checks role registry addresses, implementation slots, role constants, and if each contract saved the correct address for their partners.
> Adding a verification script for upgraded contracts with readme

- src/EtherFiNodesManager.sol
- **Before optimization**: 25,546 bytes (1,970 bytes over the 24,576 limit)
- **After optimization**: 24,106 bytes (470 bytes under the limit)
- **Total reduction**: 1,440 bytes (5.6% reduction)
- **Status**: ✅ **Now complies with EIP-170 size limit**
1. **Function Deduplication**: 
- Eliminated duplicate functions that had both `id` and `node` parameter versions
- Made the `node` versions the primary implementations (public)
- Changed `id` versions to simple wrappers that call the `node` versions
- Applied to 8+ function pairs including `getEigenPod`, `startCheckpoint`, `verifyCheckpointProofs`, `setProofSubmitter`, `queueETHWithdrawal`, `completeQueuedETHWithdrawals`, `queueWithdrawals`, and `completeQueuedWithdrawals`
2. **Helper Function Introduction**:
- Created …
> Reduce Size of EFNM
