etherfi-protocol/smart-contracts

- release/abis/EtherFiAdmin.json
- release/abis/EtherFiOracle.json
- src/EtherFiAdmin.sol
- src/EtherFiOracle.sol
- src/interfaces/IEtherFiAdmin.sol
- test/EtherFiOracle.t.sol
An oracle report with its `refBlockTo` = `x` is generated refferring to the SC states at the block = `x`.
Say the report with `refBlockTo` = `x` is published and next report with `refBlockTo` = `x + T` will follow later (T is the oracle report generation period).
Assume that the Oracle bot failed to trigger the admin task execution for the report with `refBlockTo` = `x` until the block = `x + T` and it did after the block `x + T`. Now, the next report with `refBlockTo` = `x + T` is in trouble because while it is based on the SC states at block = `x + T`, the SC states has changed by the admin task execution AFTER block = `x + T`. That is, the new report could be generated based on the past states.
The solution is to reject the Oracle report with `refBlockTo` is earlier than the last admin …
> Oracle Report must be based on the block after the last admin execution block

- script/upgrades/MultipleValidatorsPerSafe.s.sol
- src/StakingManager.sol
- test/StakingManager.t.sol
Generate the correct timelock txn data from script
````
├─ [0] VM::startBroadcast(<pk>)
│   └─ ← ()
├─ [4397838] → new LiquidityPool@0xF48dDB2b39071C8838c16c61B5017F2fE1094043
│   ├─ emit Initialized(version: 255)
│   └─ ← 22134 bytes of code
├─ [4914753] → new StakingManager@0x9f4c278A83928494bDAea44be5aFC99015076776
│   ├─ emit Initialized(version: 255)
│   └─ ← 24715 bytes of code
├─ [2267375] → new TNFT@0xd27a57BB8f9B7ec7862dF87f5143146C161f5a8B
│   ├─ emit Initialized(version: 255)
│   └─ ← 11495 bytes of code
├─ [4925971] → new EtherFiNodesManager@0xB27d4e7b8fF1EF21751b50F3821D99719Ad5868f
│   ├─ emit Initialized(version: 255)
│   └─ ← 24771 bytes of code
├─ [3179715] → new EtherFiNode@0xafb82ce44fd8a3431a64742bCD3547EEDA1AFea7
│   └─ ← 15913 bytes of code
├─ [2402] …
```
> reduced the size of StakingManager contract, improved the deploy script

- script/deploys/DeployEtherFiViewer.s.sol
- src/helpers/EtherFiViewer.sol
- test/EtherFiViewer.t.sol
`0x2ecd155405cA52a5ca0e552981fF44A8252FAb81` Deployed in mainnet
> EtherFiViewer a contract with a bunch of helpful view functions

- foundry.toml
- test/EtherFiTimelock.sol
The `EtherFiTimelock` contract is the owner of the other ether.fi contracts. The 4/7 multi-sig gnosis safe owns the EtherFiTimelock and can interact with the ether.fi contracts via the timelock as their owner.
The issue is that it is extremely difficult to use the Timelock contract even for a SC dev, because we need to (1) generate the encoded txn details manually, (2) put them into gnosis manually, which is fragile and error-prone.
As the first step to improve it, I want:
(1) to write a unit test for the timelock function call
(2) to dump the timelock schedule/execute txns so that we can just bring them to the gnosis
Steps:
1. run `forge test --mt test_updateDepositCap -vvvvv`
2. see the generated files `ls release/logs/txns/*.json`
3. given N files of such, combine them into the file …
> timelock unit test + generate the gnosis transactions

- src/EtherFiNode.sol
- src/EtherFiNodesManager.sol
- src/interfaces/IEtherFiNode.sol
- test/EtherFiNode.t.sol
- test/TestSetup.sol
The `EtherFiNode.numAssociatedValidators()` tracks the number of active validators associated with the safe. However, a safe can be locked for a certain validator before it gets fully active; i.e., while they are in  {STAKE_DEPOSITED, WAITING_FOR_APPROVA} phases.
So, in order to check if the contract is eligible for recycling, we need to check `associatedValidatorIds.length == 0` which includes the validators in {STAKE_DEPOSITED, WAITING_FOR_APPROVA} phases.
> fix recycling condition

- test/TestSetup.sol
Hello team! During tests execution I encountered the following error in `setUpTests` of the `TestSetup.sol` file:
Seems that on the [line](https://github.com/etherfi-protocol/smart-contracts/blob/4160ada6203f83e7cf776cc94eb3bb8eeccf0076/test/TestSetup.sol#L663) the `vm.startPrank(owner);` call missed to use the same owner, which deployed the contracts. This PR adds the line
> Fix missed vm.startPrank in tests

- proposals/EFIP-5.md
This EFIP aims to improve the security of ether.fi eETH/weETH by introducing a whitelist on `spender` of `permit` and a blacklist on `transfer`.
While ERC20's extension on `Permit` brings convenience by using off-chain signatures for authorization, it is a well-known vulnerability that can lead to [phishing attacks](https://cointelegraph.com/magazine/phishing-crypto-erc-20-bait-scammers/). We have also been seeing growing incidents of incidents, where eETH/weETH users are tricked into signing a permit for a malicious contract or address.
In addition, the funds can be sent to the malicious contracts or addresses by the owner or the malicious contracts can lock the funds by transferring them to the malicious addresses. This can lead to the loss of funds or the funds being locked forever.
> [EFIP-5] Security Improvements for eETH/weETH

- script/deploys/DeployEtherFiViewer.s.sol
- src/EtherFiNode.sol
- src/helpers/EtherFiViewer.sol
- src/interfaces/IEtherFiNode.sol
- test/EtherFiNode.t.sol
The upcoming Eigenlayer PEPE update removes the `hasRestaked()` function that our protocol uses in several locations. With the release of PEPE there will never be a state where previously hasRestaked would have been false, so we can safely remove those codepaths.
> Remove hasRestaked() from critical paths

- test/TestSetup.sol
When `initializeRealisticForkWithBlock(forkEnum, block.number)` is called before a fork is created, block.number defaults to 1. This causes tests calling `initializeRealisticFork()` to fail, as they expect the fork to be created at the current block.
> [Fix] forge fork testing

- proposals/EFIP-10.md
- src/EtherFiNode.sol
- src/EtherFiNodesManager.sol
- src/interfaces/IEtherFiNodesManager.sol
- test/EigenLayerIntegration.t.sol
- test/EtherFiNode.t.sol
- test/EtherFiNodesManager.t.sol
(made from @solipsis 's work merged to staging-2.5 for mainnet)
Currently, we use the blacklisting to restrict blacklisted functions from being executed. However, the blacklisting approach is not robust and can be bypassed by malicious actors by upgrade. Introducing the whitelisting will mitigate these risks by ensuring only allowed operations can be executed.
This proposes the introduction of a whitelist mechanism on the delegate call into the EtherFiNode/EigenPod contracts. This change aims to enhance security by restricting call forwarding and function execution to a predefined list of delegates, ensuring that only authorized operations can be performed.
> [EFIP-10] Whitelisted Delegate calls for EtherFiNode/EigenPod

- src/EtherFiAdmin.sol
- src/LiquidityPool.sol
- src/WithdrawRequestNFT.sol
- src/interfaces/IWithdrawRequestNFT.sol
- test/EtherFiAdminUpgrade.t.sol
- test/LrtSquare.t.sol
- test/TestSetup.sol
- test/eethPayoutUpgrade.t.sol
- Currently, the protocol relies entirely on the Oracle to process the withdrawals
- this PR enables the fast-track withdrawal processing (which does not require the Oracle consensus) to be used in the emergency such as de-peg
EFIP will follow
> allow 'WITHDRAW_NFT_ADMIN_ROLE' can perform the fast-track withdrawal

- src/LiquidityPool.sol
- src/StakingManager.sol
- src/interfaces/IStakingManager.sol
- test/AddressProvider.t.sol
- test/EtherFiNode.t.sol
- test/EtherFiNodesManager.t.sol
- test/EtherFiTimelock.sol
- test/LiquidityPool.t.sol
- test/StakingManager.t.sol
- test/TestSetup.sol
- test/Upgradable.t.sol
- Previously, we had a use case for delegate staking where a user can own a validator by staking 32 ETH. We are going to deprecate it and will keep only the Liquid Staking.
- Fix broken unit tests
> Simplify StakingManager <> LiquidityPool interaction, bug fixes, Fix broken unit tests

- .github/workflows/run-forge-tests.yaml
- audits/NM-0217 - EtherFi Deposit Adapter Contract.md
- test/DepositAdapter.t.sol
- integration testing for master branch prs
- deposit adapter audit
- fix compilation error in test
> Minor Fixes and Deposit Adapter Audit

- proposals/EFIP-4.md
- proposals/references/efip-4-nethermind-review.md
- script/upgrades/EtherFiAdminUpgradeScript.s.sol
- script/upgrades/EtherFiOracleUpgradeScript.s.sol
- script/upgrades/LiquidityPoolUpgradeScript.s.sol
- src/EtherFiAdmin.sol
- src/EtherFiOracle.sol
- src/LiquidityPool.sol
- src/interfaces/IEtherFiOracle.sol
- src/interfaces/ILiquidityPool.sol
- test/EtherFiOracle.t.sol
- test/EtherFiTimelock.sol
- test/TestSetup.sol
- test/eethPayoutUpgrade.t.sol
- test/eethPayoutUpgradeFork.t.sol
https://hackmd.io/@sK3pnSmVSxekZ0_510u48g/rkBMangsA
> [Implementation][EFIP-4] Process Fees in EETH

- src/Liquifier.sol
- test/Liquifier.t.sol
Provides a function our FE can query to get the amount of eETH a user will receive when the discount rate is applied
> Discount Pricing Function

- src/MembershipManager.sol
- test/MembershipManager.t.sol
- test/TestSetup.sol
This PR adds a manual tracking for the number of EETH shares owned by the membership manager. This prevents anyone from being able to impact rebasing operations via donating eETH shares to the membership manager
Primary testing provided by the existing `test_bring_random_monkeys()` function. At the conclusion of this function with thousands of deposit / rebase / withdrawal operations, shares are within 5000 shares of the target amount which is just dust.
> [Certora] [M-10] + [M-11] Manual tracking of EETH shares owned by membership manager

- src/Liquifier.sol
- test/Liquifier.t.sol
- test/TestSetup.sol
Some features have been added to the production liquifier contract. This pr integrates these features our v2.5 branch:
- https://github.com/etherfi-protocol/smart-contracts/pull/188
- https://github.com/etherfi-protocol/smart-contracts/pull/190
> Integrate Liquifier Changes

- script/deploys/DeployEtherFiOperationParameters.s.sol
- src/helpers/EtherFiOperationParameters.sol
- test/EtherFiOperationParameters.t.sol
This contract acts as a configurable coordination layer that lets administrators update operational parameters using tags and keys. Tags function as namespaces containing key-value pairs for different settings. Admins can be granted or revoked access to update parameters within specific tags, with all changes tracked through emitted events.
The contract provides on-chain storage for protocol settings and permissions, managing both admin access (tagAdmins) and parameter values (tagKeyValues). Frontend and backend systems can then operate automatically based on these configurations.
This is a pure parameter registry, for now. but it can have additional smart contract logics and permissions depending on our needs
Deploed at https://etherscan.io/address/0xd0ff8996db4bdb46870b7e833b7532f484fead …
> add EtherFiOperationParameters

- script/deploys/DeployEtherFiViewer.s.sol
- src/helpers/EtherFiViewer.sol
* Removed methods that no longer have a non-deprecated equivalent
* Updated methods with that have a mostly equivalent call
> slashing update etherfi viewer

- src/EtherFiNode.sol
- src/EtherFiRestaker.sol
- test/EtherFiNode.t.sol
- test/EtherFiRestaker.t.sol
- test/TestSetup.sol
- **EtherFiNode**
- at `splitBalanceInExecutionLayer`, convert the share amount to the underlying asset amount
- at `_queueEigenpodFullWithdrawal`, convert the share amount to the underlying asset amount + withdraw the full amount if it is the last validator of the pod
- **EtherFiRestaker**
- update according to EigenLayer upgrade
- deprecate the contract variable `withdrawalRootToWithdrawal`. the upgrade will be performed when there is no queued withdrawal. 
- keep `withdrawalRootsSet` to help track the queued withdrawals
- use `quoteByFairValue` where needed
- add `selClaimerFor`
> [EigenLayer Slashing] (1) update EtherFiRestaker, (2) fixes in EtherFiNode

- script/deploys/DeployEtherFiViewer.s.sol
- src/EtherFiNode.sol
- src/EtherFiNodesManager.sol
- src/EtherFiRestaker.sol
- src/helpers/EtherFiViewer.sol
- src/interfaces/IEtherFiNode.sol
- test/EigenLayerIntegration.t.sol
- test/EtherFiNode.t.sol
- test/EtherFiRestaker.t.sol
- test/TestSetup.sol
- removed the usage of `middlewareTimesIndexes`
- removed the usage of `eigenPod.balance`
- updated `splitBalanceInExecutionLayer`, `totalBalanceInExecutionLayer`, `withdrawableBalanceInExecutionLayer`
- removed the deprecated delayedWithdrawal router code
- used the provided functions by EL
- deprecated EtherFiNode's {`pendingWithdrawalFromRestakingInGwei`, `completedWithdrawalFromRestakingInGwei`}
- `_queueEigenpodFullWithdrawal` is fixed so that the beacon withdrawal <32 eth can be processed
- marked all contracts & tests broken with `FIX BELOW`. these are TODOs
- TODO: write tests
> [EigenLayer Slashing] EtherFiNodesManager & EtherFiNode

- src/EtherFiNode.sol
- test/ArrayTestHelper.sol
- test/EtherFiNode.t.sol
- test/TestSetup.sol
- test/eigenlayer-mocks/DelegationManagerMock.sol
- test/eigenlayer-mocks/MockDelegationManager.sol
- test/eigenlayer-mocks/MockEigenPod.sol
- test/eigenlayer-mocks/MockEigenPodManager.sol
- test/eigenlayer-mocks/MockStrategy.sol
* INCLUDES A SINGLE LINE CHANGE TO `EtherfiNode.sol` that improves mock testing setup
* Mocks for core eigenlayer contracts required for withdrawals
* Helper library for arrays to clean up our code frequently creating arrays of 1 item
* Tests for
* withdrawing last unslashed validator
* withdrawing last slashed validator
* withdrawing last validator with rewards
* withdrawing non-final validator
> El slashing mock testing

- src/EtherFiNodesManager.sol
the ETH validators earn the staking rewards and they are sent to the `EtherFiNode` contracts. 
Process of sweeping those ETH is called `partialWithdraw`.
Currently, `EtherFiNodesManager.partialWithdraw` can't process the withdrawal beyond 16 ETH 
because the `EtherFiNodesManager._getTotalRewardsPayoutsFromSafe` reverts if the contract's balance >= 16 ETH.
This constraint was added in the past due to the complexity in handling the distribution of staking rewards and principal (= 32 ETH); while the earned staking rewards were distributed to (T-NFT, B-NFT, NodeOperator, Treasury), the principal (32 ETH) were sent to (B-NFT, T-NFT).
This complexity was removed while ago and now the below constraints are true:
- for all validators, its T-NFT holder == B-NFT holder
- `stakingRewardsSplit.tnft` …
> Update `partialWithdraw` to sweep ETH from EtherFiNode contracts

- src/EtherFiNode.sol
- src/EtherFiNodesManager.sol
- src/eigenlayer-interfaces/IEigenPod.sol
- src/interfaces/IEtherFiNode.sol
- src/interfaces/IEtherFiNodesManager.sol
- test/mocks/MockEigenPodBase.sol
- test/prelude.t.sol
This PR implements EIP-7251 validator consolidation functionality for the etherFi protocol, following the same EIP-7002 withdrawal request patterns. This enables validator consolidation and switching from `0x01` to `0x02` (compounding withdrawal credentials)
- Combine multiple validators into single validators with up to 2,048 ETH
- Switch validators from `0x01` to `0x02` credentials for automatic reward compounding
- Up to 64x reduction in proof size and gas costs for large restakers
> feat: add validators consolidation support EIP-7251

- script/V3PreludeTransactions.sol
- src/EtherFiNode.sol
- src/EtherFiNodesManager.sol
- src/StakingManager.sol
- src/interfaces/IEtherFiNode.sol
- src/interfaces/IEtherFiNodesManager.sol
- src/interfaces/IStakingManager.sol
- test/EtherFiRateLimiter.t.sol
- test/common/ArrayTestHelper.sol
- test/prelude.t.sol
* Staking manager tracks all etherFiNode contracts it deploys
* admin method to backfill old node date
* All key methods of etherFiNode now called from EFNM. No more direct calls
* Remove lots of unused roles from above change
* No more circular dependencies rate limits
* remove UNRESTAKER role from EFNM that is no longer necessary
* New POD_PROVER role so prover server can be removed from forwarding whitelist improving security
* Handful of small dev-xp changes for painpoints after v3-prelude
Multiple tests that need to be fixed, and new tests for some of the new functionality need to be written
> WIP: track deployed nodes which enables many refactors

- src/EtherFiNodesManager.sol
- src/interfaces/IEtherFiNodesManager.sol
- test/prelude.t.sol
Implemented a new granular call forwarding whitelist strategy for `EtherFiNodesManager` that adds user-specific permissions instead of the previous function-level permissions. This addresses security concerns where hot wallets with `CALL_FORWARDER_ROLE` had access to all whitelisted functions.
```solidity 
// OLD - Function-level permissions
mapping(bytes4 => bool) public allowedForwardedEigenpodCalls;
mapping(bytes4 => mapping(address => bool)) public allowedForwardedExternalCalls;
// NEW - User-specific permissions
mapping(address => mapping(bytes4 => bool)) public allowedForwardedEigenpodCalls;
mapping(address => mapping(bytes4 => mapping(address => bool))) public allowedForwardedExternalCalls;
```
- Updated `IEtherFiNodesManager` interface to match new function signatures
- …
> feat: new call forwarding strategy
